---
# A local development environment
version: '3'

networks:
  jonathonball:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.70.0/24

services:

  nginx:
    image: nginx:alpine
    command: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ..:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - jonathonball

  php-fpm:
    build:
      context: ./php-fpm
    working_dir: /var/www
    volumes:
      - ..:/var/www
    networks:
      - jonathonball

  # composer: # exits
  #   image: composer:latest
  #   restart: 'no'
  #   command: install
  #   volumes:
  #     - ..:/app
